"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import datetime
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p976(2qh=6je)@awj@ijnex@ty^o$z9dipn-7!0sh*w9!=m(d)'

# JWT Token Settings
JWT_SETTINGS = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(days=1),  # Token expires in 1 day
    "ALGORITHM": "HS256",  # Hashing algorithm
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.admin_panel',  # Registering the app
    # 'admin_panel',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "apps.admin_panel.middlewares.authmiddleware.JWTAuthenticationMiddleware", #Auth Middleware
    "apps.admin_panel.middlewares.commonmiddleware.IPAddressMiddleware" #common middleware (ipaddress)
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # this line is added
        'DIRS': [os.path.join(BASE_DIR, 'apps/admin_panel/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.admin_panel.context_processors.site_title',

            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#MYSQL Database Connection
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_pannel_setup',   #name of the database
        'USER': 'root',  #usename
        'PASSWORD': '12345',    # your MySQL password
        'HOST': '127.0.0.1',        # Use '127.0.0.1' for localhost
        'PORT': '3306',             #port to connect
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME': 'db_sudacg_system',
#         'USER': '',
#         'PASSWORD': '',
#         'HOST': 'WIN-6UH5NBIK6J2',  # Or your SQL Server instance name
#         'PORT': '1433',      # Default SQL Server port
        
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',
#              'trusted_connection': 'yes',  # Windows Auth
#             'TrustServerCertificate': 'yes',  # Required for self-signed certs
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# below code is added
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "apps/admin_panel/static")
]

# Site title for dashboard
SITE_TITLE = "Admin Panel"
